Document: dooropener
Title: Debian dooropener Manual
Author: <insert document author here>
Abstract: This manual describes what dooropener is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dooropener/dooropener.sgml.gz

Format: postscript
Files: /usr/share/doc/dooropener/dooropener.ps.gz

Format: text
Files: /usr/share/doc/dooropener/dooropener.text.gz

Format: HTML
Index: /usr/share/doc/dooropener/html/index.html
Files: /usr/share/doc/dooropener/html/*.html
